#############################################################################
# Makefile for building: pq_linux
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 5? 29 17:33:50 2020
# Project:  pq_linux.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile pq_linux.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../TOOLS/libpcap-1.9.1 -I/usr/local/fftw-3.3.8/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -L/home/pi/SUN/PQ/pq_pi_3to1_20/../../TOOLS/libpcap-1.9.1/ -lpcap -L/home/pi/SUN/PQ/pq_pi_3to1_20/../../../../../usr/local/fftw-3.3.8/lib/ -lfftw3 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		pq_linux.cpp \
		net_init.cpp \
		data.cpp \
		dlist.cpp \
		socket_send.cpp \
		tool.cpp \
		V_Dip_Swell_Interrupt.cpp \
		workthread.cpp moc_pq_linux.cpp
OBJECTS       = main.o \
		pq_linux.o \
		net_init.o \
		data.o \
		dlist.o \
		socket_send.o \
		tool.o \
		V_Dip_Swell_Interrupt.o \
		workthread.o \
		moc_pq_linux.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		pq_linux.pro
QMAKE_TARGET  = pq_linux
DESTDIR       = 
TARGET        = pq_linux

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/pi/SUN/PQ/pq_pi_3to1_20/../../TOOLS/libpcap-1.9.1/libpcap.a /home/pi/SUN/PQ/pq_pi_3to1_20/../../../../../usr/local/fftw-3.3.8/lib/libfftw3.a ui_pq_linux.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: pq_linux.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile pq_linux.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile pq_linux.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pq_linux1.0.0 || $(MKDIR) .tmp/pq_linux1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pq_linux1.0.0/ && $(COPY_FILE) --parents pq_linux.h net_init.h data.h dlist.h main.h socket_send.h tool.h V_Dip_Swell_Interrupt.h workthread.h .tmp/pq_linux1.0.0/ && $(COPY_FILE) --parents main.cpp pq_linux.cpp net_init.cpp data.cpp dlist.cpp socket_send.cpp tool.cpp V_Dip_Swell_Interrupt.cpp workthread.cpp .tmp/pq_linux1.0.0/ && $(COPY_FILE) --parents pq_linux.ui .tmp/pq_linux1.0.0/ && (cd `dirname .tmp/pq_linux1.0.0` && $(TAR) pq_linux1.0.0.tar pq_linux1.0.0 && $(COMPRESS) pq_linux1.0.0.tar) && $(MOVE) `dirname .tmp/pq_linux1.0.0`/pq_linux1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pq_linux1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_pq_linux.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_pq_linux.cpp
moc_pq_linux.cpp: pq_linux.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) pq_linux.h -o moc_pq_linux.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_pq_linux.h
compiler_uic_clean:
	-$(DEL_FILE) ui_pq_linux.h
ui_pq_linux.h: pq_linux.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic pq_linux.ui -o ui_pq_linux.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp pq_linux.h \
		net_init.h \
		workthread.h \
		socket_send.h \
		main.h \
		dlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pq_linux.o: pq_linux.cpp pq_linux.h \
		ui_pq_linux.h \
		workthread.h \
		socket_send.h \
		V_Dip_Swell_Interrupt.h \
		main.h \
		dlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pq_linux.o pq_linux.cpp

net_init.o: net_init.cpp ../../TOOLS/libpcap-1.9.1/pcap.h \
		../../TOOLS/libpcap-1.9.1/pcap/pcap.h \
		../../TOOLS/libpcap-1.9.1/pcap/funcattrs.h \
		../../TOOLS/libpcap-1.9.1/pcap/compiler-tests.h \
		../../TOOLS/libpcap-1.9.1/pcap/pcap-inttypes.h \
		../../TOOLS/libpcap-1.9.1/pcap/socket.h \
		../../TOOLS/libpcap-1.9.1/pcap/bpf.h \
		../../TOOLS/libpcap-1.9.1/pcap/dlt.h \
		workthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o net_init.o net_init.cpp

data.o: data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

dlist.o: dlist.cpp dlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlist.o dlist.cpp

socket_send.o: socket_send.cpp socket_send.h \
		workthread.h \
		main.h \
		dlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socket_send.o socket_send.cpp

tool.o: tool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tool.o tool.cpp

V_Dip_Swell_Interrupt.o: V_Dip_Swell_Interrupt.cpp V_Dip_Swell_Interrupt.h \
		workthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V_Dip_Swell_Interrupt.o V_Dip_Swell_Interrupt.cpp

workthread.o: workthread.cpp workthread.h \
		/usr/local/fftw-3.3.8/include/fftw3.h \
		tool.h \
		V_Dip_Swell_Interrupt.h \
		main.h \
		dlist.h \
		pq_linux.h \
		data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workthread.o workthread.cpp

moc_pq_linux.o: moc_pq_linux.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pq_linux.o moc_pq_linux.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/pq_linux/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/pq_linux/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/pq_linux/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/pq_linux/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/pq_linux/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

